# Generated by Django 5.1.2 on 2024-11-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramId',
        ),
    ]
