# Generated by Django 5.1.2 on 2024-11-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_delete_telegramid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='nutritional_value',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
