# Generated by Django 5.1.2 on 2024-11-28 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_recipes_nutritional_value_delete_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('count', models.IntegerField()),
                ('time', models.CharField(max_length=10)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('photos', models.TextField()),
                ('nutritional_value', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.nutritionalvalue')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
