# Generated by Django 5.1.2 on 2024-11-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
