# Generated by Django 5.1.2 on 2024-12-04 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_recipes_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='recommended',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.TextField(verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='nutritional_value',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.nutritionalvalue', verbose_name='Пищевая ценность'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='photos',
            field=models.TextField(verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='steps',
            field=models.TextField(verbose_name='Шаги приготовления'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='time',
            field=models.CharField(max_length=30, verbose_name='Время пригтовления'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Название'),
        ),
    ]
