# Generated by Django 5.1.2 on 2024-12-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_remove_recipes_recommended_alter_recipes_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='count',
            field=models.IntegerField(verbose_name='Количество порций'),
        ),
    ]
