# Generated by Django 5.1.2 on 2024-12-21 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='norm_of_nutrients',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Норма нутриентов'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='tg_id',
            field=models.IntegerField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
